[package]
name = "cosmos-snapshot-lite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ocular = { version = "1.0.0-alpha" }
eyre = { version = "0.6.8" }
tokio = "1.20.1"